name: Build multiarch image - tag

on:
  release:
    types: [published]
  
jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci-skip]')"
    steps:

      - name: Get latest tag
        id: vars
        run: echo "tag=${GITHUB_REF:10}" >> ${GITHUB_OUTPUT}

      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: ${{ steps.vars.outputs.tag }}

      - name: Prepare
        id: prep
        run: |
          BUILD_DATE=$(date --rfc-3339=seconds --utc)
          echo "build_date=${BUILD_DATE}" >> ${GITHUB_OUTPUT}
          PLATFORMS=amd64,arm,arm64
          REPO_OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          TAGS1="ghcr.io/${REPO_OWNER}/tor:${{ steps.vars.outputs.tag }}"
          if [ "${{github.event_name}}" == "pull_request" ]; then
                echo "push=false" >> ${GITHUB_OUTPUT}
              else
                echo "push=true" >> ${GITHUB_OUTPUT}
                echo "tags1=${TAGS1}" >> ${GITHUB_OUTPUT}
                echo "branch=${GIT_BRANCH}" >> ${GITHUB_OUTPUT}
          fi
          echo "platforms=${PLATFORMS}" >> ${GITHUB_OUTPUT}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: ${{ steps.prep.outputs.platforms }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
          version: latest
          driver-opts: image=moby/buildkit:latest

      - name: Build and push (tor)
        uses: docker/build-push-action@v2
        with:
          labels: |
            org.opencontainers.image.created=${{ steps.prep.outputs.build_date }}
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: Dockerfile
          platforms: ${{ steps.prep.outputs.platforms }}
          push: ${{ steps.prep.outputs.push }}
          tags: ${{ steps.prep.outputs.tags1 }}
      
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.33.1
        with:
          image-ref: ${{ steps.prep.outputs.tags1 }}
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
