name: Daily Trivy Scan

on:
  schedule:
    - cron: '56 8 * * *' # Runs every day
  workflow_dispatch:

jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read   # needed to checkout the repo
      packages: read   # needed to pull images from GitHub Container Registry (if used)

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: 'Get Recent tag'
        id: recentTag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"

      - name: Get tags to scan
        id: tags
        run: |
          REPO_OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          IMAGE="ghcr.io/${REPO_OWNER}/tor"
          LATEST_TAG="latest"
          RECENT_TAG=${{ steps.recentTag.outputs.tag }}

          echo "image=$IMAGE" >> $GITHUB_OUTPUT
          echo "latest=$LATEST_TAG" >> $GITHUB_OUTPUT
          echo "recent=$RECENT_TAG" >> $GITHUB_OUTPUT
      
      - name: Scan latest tag
        id: scanLatest
        continue-on-error: true
        uses: aquasecurity/trivy-action@0.33.1
        with:
          image-ref: ${{ steps.tags.outputs.image }}:${{ steps.tags.outputs.latest }}
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
      
      - name: Scan recent tag
        id: scanRecent
        continue-on-error: true
        uses: aquasecurity/trivy-action@0.33.1
        with:
          image-ref: ${{ steps.tags.outputs.image }}:${{ steps.tags.outputs.recent }}
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Fail job if scan failed
        if: steps.scanLatest.outcome == 'failure' || steps.scanRecent.outcome == 'failure'
        run: |
          echo "::error ::One or more checks failed."
          exit 1
